---
name: azure-service-fabric

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: azure-service-fabric
  azs: [z1, z2, z3]
  instances: 5
  vm_type: service-fabric
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: azure-service-fabric
    release: azure-service-fabric
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 2
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 3
  serial: false

releases:
- name: bpm
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
  version: 0.5.0
- name: azure-service-fabric
  sha1: 496012528d88f516bf27fb5414dabe0fe1645b79
  url: https://github.com/starkandwayne/azure-service-fabric-boshrelease/releases/download/v0.1.0/azure-service-fabric-0.1.0.tgz
  version: 0.1.0
