---
name: azure-service-fabric

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: azure-service-fabric
  azs: [z1, z2, z3]
  instances: 1
  vm_type: service-fabric
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: azure-service-fabric
    release: azure-service-fabric
    properties: {}

variables: []

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  version: 0.5.0
  url: git+https://github.com/cloudfoundry-incubator/bpm-release
- name: azure-service-fabric
  version: latest # TODO: update after first final release
  # url:            TODO: update after first final release
  # sha1:           TODO: update after first final release
