---
meta:
  name:    azure-service-fabric
  target:  ohio-cf
  url:     https://ci2.starkandwayne.com

  test-errand: ~

  initial_version: 0.1.0

  git:
    email:  ((git-commit-email))
    name:   ((git-commit-name))

  bosh:
    target:   ((bosh_environment))
    cacert:   ((bosh_ca_cert))
    username: ((bosh_client))
    password: ((bosh_client_secret))

  aws:
    bucket:      (( grab meta.pipeline ))
    region_name: us-east-1
    access_key:  ((aws-access-key))
    secret_key:  ((aws-secret-key))

  github:
    owner:  starkandwayne
    repo:   (( grab meta.pipeline ))
    branch: master
    private_key:  ((github-private-key))
    access_token: ((github-access-token))

  slack:
    webhook:       ((slack-webhook))
    username:      ((slack-username))
    icon:          ((slack-icon-url))
    channel:       (( concat meta.name "-boshrelease" ))
    blob_success:  '(( concat ": New version of  was detected, and updated in master. <" meta.url "/teams//pipelines/| Cut a new release?>" ))'
    blob_failure:  '(( concat ": :airplane_arriving: <" meta.url "/teams//pipelines//jobs//builds/| Failed to update the blob for >" ))'
